name: Deploy NGINX Container

on:
  push:
    branches:
      - main

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

    - name: Deploy NGINX Container
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<YOUR_EC2_PUBLIC_IP> << 'EOF'
        sudo docker pull nginx
        sudo docker run -d -p 80:80 --name nginx-container nginx
        EOF
