name: SSH into EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.82.15.99 << 'EOF'
            echo "Successfully connected to EC2 instance!"
            # Add any other commands you want to run on the EC2 instance here
          EOF
